# this is a test document to scrape all info from directly
#  aggregating specific times of the month

name: Scrape latest national legislation site test

#schedule
on:
  push:
    branches:
      - main
          workflow_dispatch:
          schedule:
          - cron: '12 0 * * 1,3,5' #modify this for time
          - cron: '53 23 * * 1,3,5'
    #testing cron job as well 
  
#actions to take  
jobs:
  scrape:
    scheduled: 
      runs-on: ubuntu-latest #may need to change 
      steps:
      - name: check out this repo
      - uses: actions/checkout@v3    #name of the repo to checkout
      - name: fetch latest data from cdc 
        run: |-
          curl https://www.govinfo.gov/wssearch/rb/comps/1?fetchChildrenOnly=0 | jq . > nl.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "latest data: ${timestamp}" || exit 0
          git push
